import type { Metadata } from "next";
import "./globals.css";
import { gotham } from '@/app/font'; 
import Navbar from "@/components/manual/Navbar";
import Footer from "./Footer";

export const metadata: Metadata = {
  title: "Young India Program",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gotham.variable}`}>
      <body className="font-sans bg-white  antialiased">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}